version: '3.1'

services:
  rest:
    build: .
    image: doorplates
    ports:
      - "8080:8080"
    environment:
      - INKSCAPE_URL=http://inkscape:8080
      # if no specific directories are defined, subdirectories in the data directory will be used
      - DATA_DIRECTORY=/data/
      #- TEMPLATES_DIRECTORY=/data/templates
      #- DOORPLATES_DIRECTORY=/data/doorplates
      - RENDERING_BACKEND=inkscape-microservice
      #- RENDERING_BACKEND=inkscape
      #- RENDERING_BACKEND=cairosvg
      #- RENDERING_BACKEND=svglib
  inkscape:
    image: registry.gitlab.com/debuglevel/inkscape-converter-microservice:0-0-6
    environment:
      - DATA_DIRECTORY=/data